from __future__ import print_function

import argparse
import sys

def die(s):
    sys.stderr.write(s + '\n')
    sys.exit(1)

parser = argparse.ArgumentParser(description=
        'Convert ACME constant definitions to PLASMA.')
parser.add_argument('input', metavar='INPUT', type=argparse.FileType('r'), help="input file (simple ACME source file)")

args = parser.parse_args()

print("// AUTOGENERATED; DO NOT EDIT THIS FILE - edit %s instead\n" % args.input.name)

for line in args.input:
    line = line[:-1]
    i = line.find(";")
    if i == -1:
        code = line
        comment = ""
    else:
        code = line[:i]
        comment = line[i:].replace(";", "//", 1)
        comment = comment.strip()
        if comment != "":
            comment = " " + comment.strip()
    if code.strip() != "":
        if code.find("=") != -1:
            code = "const " + code.lower()
        elif code.find("!IFDEF") != -1 or code.find("!IFNDEF") != -1 or code.find("ELSE") != -1 or code.find("}") != -1:
            code = code.replace("!IFDEF", "#ifdef")
            code = code.replace("!IFNDEF", "#ifndef")
            code = code.replace("{", "")
            code = code.replace("}", "#endif")
        else:
            die("Unable to convert line: " + line)
    print(code + comment)
