PORT = apple

.PHONY: apple
apple: foo.ssd

# SAMPLESRC and LIBSRC are defined on a per-port basis since not all will
# be available on all ports.
SAMPLESRC = sieve.pla hello.pla rod.pla
LIBSRC = conio.pla fileio.pla joybuzz.pla

include makefile.common

foo.ssd: $(ALLOBJ)
	# TODO: We use tar as a demo substitute for a platform specific 'make
	# a disk image' command
	tar cvf $@ $(ALLOBJ)
