PLASM = ./plasm
PLVMZP = vmsrc/plvmzp.inc
PORT = acorn
REL = rel/$(PORT)/
RELINT = $(REL)int/ # intermediate

# Assumption: we won't have two source files with the same name unless they are alternate
# versions for different ports. The pay off for this is that we can use VPATH to locate
# source files without any fuss, and we can just put all the compiled modules into a flat
# directory structure.

SAMPLESRC = sieve.pla hello.pla
LIBSRC = conio.pla fileio.pla
ALLSRC = $(SAMPLESRC) $(LIBSRC)
ALLOBJ = $(addprefix $(REL),$(patsubst %.pla,%.plm,$(ALLSRC)))

VPATH = libsrc/$(PORT):samplesrc/$(PORT):libsrc:samplesrc

all: foo.ssd

$(PLVMZP):
	cd vmsrc && ln -sf $(PORT)/plvmzp.inc plvmzp.inc

rel/$(PORT)/%.plm: %.pla $(PLVMZP)
	$(eval INT := $(addsuffix .s,$(addsuffix $(basename $(notdir $<)),$(RELINT))))
	$(PLASM) -AMOW < $< > $(INT)
	acme --setpc 4094 -o $@ $(INT)

#rel/$(PORT)/samplesrc/sieve.plm: sieve.pla
#	touch $@

#foo.ssd: $(SAMPLEOBJ) $(LIBOBJ)
#foo.ssd: rel/acorn/sieve.plm
foo.ssd: $(ALLOBJ)
	echo sampleobj $(SAMPLEOBJS)
	echo libobj $(LIBOBJS)
