PLASM = ./plasm
PORT = acorn
REL = rel/$(PORT)
RELINT = $(REL)/int/ # intermediate
SAMPLESRC = samplesrc/sieve.pla samplesrc/hello.pla
#SAMPLEOBJ = $(patsubst %.pla,$(REL)/%.plm,$(SAMPLESRC))
SAMPLEOBJ = $(subst samplesrc,rel/$(PORT)/sample,$(patsubst %.pla,%.plm,$(SAMPLESRC)))
LIBSRC = libsrc/$(PORT)/conio.pla libsrc/$(PORT)/fileio.pla
LIBOBJ = $(subst libsrc/$(PORT),rel/$(PORT)/lib,$(patsubst %.pla,%.plm,$(LIBSRC)))

all: foo.ssd

rel/$(PORT)/sample/%.plm: samplesrc/%.pla
	$(eval INT := $(addsuffix $(basename $<),$(RELINT)))
	$(PLASM) -AMOW < $< > $(INT)
	acme --setpc 4094 -o $@ $(INT)

rel/$(PORT)/lib/%.plm: libsrc/$(PORT)/%.pla
	$(PLASM) -AMOW < $< > xxx
	acme --setpc 4094 -o $@ xxx

#rel/$(PORT)/samplesrc/sieve.plm: sieve.pla
#	touch $@

foo.ssd: $(SAMPLEOBJ) $(LIBOBJ)
	echo sampleobj $(SAMPLEOBJ)
	echo libobj $(LIBOBJ)
